[package]
name = "coins_to_spend_poc"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
hex = "0.4.3"
postcard = { version = "1.0.10", features = ["alloc"] }
rand = "0.8.5"
rocksdb = "0.22.0"
serde = { version = "1.0.215", features = ["derive"] }
